### ISSUE TITLE
[question] how is Backlinks generated in the markdown files

### ISSUE THREAD

**Issue by showgood** [jethrokuan/braindump#19]
I really like the your braindump website, looks great and very useful.

I tried to mimic it but one thing I didn't figure out is how are the backlinks in the markdown files are generated?  I think ox-hugo doesn't add that in my case. 

For eg, books.md has something likes this:
```
## Backlinks {#backlinks}

-   [How To Take Smart Notes]({{< relref "how_to_take_smart_notes" >}})
```

Thanks a lot for your work!!

**Comment by jethrokuan** [comment]
How backlinks are added to org export is explained a bit here:

https://org-roam.readthedocs.io/en/latest/org_export/

**Comment by showgood** [comment]
thanks a lot!! It works now!

**Comment by panmengguan** [comment]
> How backlinks are added to org export is explained a bit here:
> 
> https://org-roam.readthedocs.io/en/latest/org_export/

Sorry to mention this again, I have the same question, but this readthedocs link is expired.

**Comment by jethrokuan** [comment]
They are now entirely generated by my theme (https://github.com/jethrokuan/cortex/blob/5e5fd537bed363d12fa297a4b1603ff56dbf397b/layouts/partials/backlinks.html)

**Comment by panmengguan** [comment]
> They are now entirely generated by my theme (https://github.com/jethrokuan/cortex/blob/5e5fd537bed363d12fa297a4b1603ff56dbf397b/layouts/partials/backlinks.html)

That's great! Does that mean that we don't have to publish all the og-roam files in order to update the backlinks? I use the solution of (https://github.com/org-roam/org-roam/issues/156#issuecomment-590030752), but one of the main problem is that, I have to republish all the org-roam files including those unmodified to make the published backlinks right. Thank you very much!

**Comment by jethrokuan** [comment]
> > 
> 
> That's great! Does that mean that we don't have to publish all the og-roam files in order to update the backlinks? I use the solution of ([org-roam/org-roam#156 (comment)](https://github.com/org-roam/org-roam/issues/156#issuecomment-590030752)), but one of the main problem is that, I have to republish all the org-roam files including those unmodified to make the published backlinks right. Thank you very much!

You still have to republish (org -> md), but only the files that are changed, since backlinks computation is done at a later phase.

**Comment by panmengguan** [comment]
> > > 
> > 
> > 
> > That's great! Does that mean that we don't have to publish all the og-roam files in order to update the backlinks? I use the solution of ([org-roam/org-roam#156 (comment)](https://github.com/org-roam/org-roam/issues/156#issuecomment-590030752)), but one of the main problem is that, I have to republish all the org-roam files including those unmodified to make the published backlinks right. Thank you very much!
> 
> You still have to republish (org -> md), but only the files that are changed, since backlinks computation is done at a later phase.

Thank you very much! That already solves my problem, since the change is incremental, only a small portion of the files in the org-roam database is changed each time.
