### ISSUE TITLE
How to make the automatic export of org-roam files

### ISSUE THREAD

**Issue by alvarmaciel** [jethrokuan/braindump#31]
Hi, 
I'm very happy using org-roam. Now I'm trying to make public my notes. But I really don't know how to make the automatic export of my orgfiles in my Dropbox folder to my content file. 
Can you explain me the process?
thanks

**Comment by jethrokuan** [comment]
Hi, the setup is really complex tbh. I use `ox-hugo`, and wrote about it here: https://blog.jethro.dev/posts/automatic_publishing/

**Comment by alvarmaciel** [comment]
Thanks, I read it, and actually I can make the automatic exportation (I have to be honest, with a lot of copy paste of your config). The issue that I can not solve is that wen I make a new relation in a note, that relationship, is not updated. 
For example. I have a note A with a link (org.roam-insert) to B. When I revisit the note I add a new relation to C but when is exported, this relation don't appear... 
But now that I'm writing this, maybe this is not the correct way to make smart notes, I should have to make a new note with de A-B-C relation, don't you think?

**Comment by jethrokuan** [comment]
yup, I don't have any configuration to re-export notes with links. The web export is not something I treat first class, since I deal mainly with reading using Emacs.

**Comment by alvarmaciel** [comment]
I finally do it. I just have to make an ogr-export All Subtrees or files to MD at the end of the day ando update all backlinks on my publish site

**Comment by alvarmaciel** [comment]
tha solution that i make wrote before was wrong

**Comment by jethrokuan** [comment]
The theme now does the backlinks generation, rather than Emacs.
