### ISSUE TITLE
Possible to share ox-hugo setup?

### ISSUE THREAD

**Issue by anthrolisp** [jethrokuan/braindump#34]
I really love this setup, especially from org-roam to a beautiful hugo website. Is it possible for you to share the relevant files and setup so that others can replicate it? Additionally, is there a way to mark which files or perhaps a subfolder of files in the org-roam directory that would be exported (say if one wanted some files not to be exported)? Thank you in advance!!!

**Comment by hraban** [comment]
@anthrolisp I've added instructions in the readme to compile the project. Give them a shot: on my machine it results in the complete website, as is hosted online. Is that what you meant?

**Comment by holtzermann17** [comment]
@hraban The patch you added certainly helps explain some of the workflow, but it doesn't explain the `ox-hugo` part of the workflow. 

> "This braindump is generated via ox-hugo" 

Can you add some more information?  For example, having deleted all of the markdown files, how do I then regenerate them?

**Comment by hraban** [comment]
Ahh of course, gotcha. Sorry I completely forgot for some reason. That's here: https://github.com/jethrokuan/dots/blob/0064ea2aab667f115a14ce48292731db46302c53/.doom.d/config.el#L488

```emacs-lisp
  (defun jethro/org-roam-export-all ()
    "Re-exports all Org-roam files to Hugo markdown."
    (interactive)
    (dolist (f (org-roam--list-all-files))
      (with-current-buffer (find-file f)
        (when (s-contains? "SETUPFILE" (buffer-string))
          (org-hugo-export-wim-to-md)))))
```

**Comment by jethrokuan** [comment]
I've added a bit more details for generation into the README. I now use Ninja and Emacs to do the exporting.
