### ISSUE TITLE
is there a way to install your package other than nix?

### ISSUE THREAD

**Issue by dineshbhardwaj** [jethrokuan/braindump#36]
NIX need lot of space and hand calibration on Mac. It won't be easy to do that since i am low on disk volume. Could you please suggest other then nix way to install your package ??

**Comment by jethrokuan** [comment]
What package are you referring to?

**Comment by hraban** [comment]
@dineshbhardwaj let me know if the new instructions in the readme work on your machine. Shouldn't need nix to follow them.
