### ISSUE TITLE
I just need some help ^^

### ISSUE THREAD

**Issue by Cletip** [jethrokuan/braindump#41]
Hi, first of all,thanks for posting your braindump (and org roam, it's really a great tool) .
Second, it's not really a "real issue", but I'm a bit confused and I think this will help other people too: I can't get Ninja to work with this repo. 

I summarize: I downloaded the repository, I make a ./build.py. The output: ninja: no work to do. Perfect!

git submodule init
git submodule update

Yhea easy
And finally : 
hugo server

Ok perfect !

Now I want to modify files, and it comes with several problems.

When I modify a file, I do a ./build.py, and I get the following output: ninja: no work to do. Hum, strange
First problem. 
I look at build.py, and I spend A LOT of time to except find the problem.

And I can't find any solutions. 
I have a clue: when I modify the files to be taken in ./build.py, the conversion starts and... never ends. YES. Second problem

No matter how hard I look at the problem, I can't do anything about it, but above all: I don't have any leads left to look for (I haven't managed to see the solution).

Thank you in advance for your future answers

**Comment by wn** [comment]
Does `files = glob.glob("org/**/*.org")` works for you?

**Comment by Cletip** [comment]
Thank you for your answer
No it's not a problem of path, but rather at the level of ninja. 

I solved my problem : python installation not in the right place, ninja installation properly, modification of all variables in build.py

The only problem is that the links don't work. This comes from my init.el, I think I'll do that later.

Thanks for your attention!
