### ISSUE TITLE
~/.emacs.d/init.el file

### ISSUE THREAD

**Issue by yanboyang713** [jethrokuan/braindump#44]
Hello @jethrokuan,

Good day to you.

I saw your **build.py** based on your ~/.emacs.d/init.el

Could you share your init.el?

I am using Doom Emacs, I found ninja run emacs could NOT point to my Doom Configuration.
I guess this is reason why you are using init.el.

Have a nice day,
Boyang Yan

**Comment by jethrokuan** [comment]
you can find it here https://github.com/jethrokuan/dots/tree/master/.doom.d

**Comment by yanboyang713** [comment]
Thanks @jethrokuan
